Editing when the item is pressed
terryperun/ToDoRN pull request #3
Opened 2019-01-28 14:22 UTC by terryperun

2019-01-29 10:46 UTC, terrysahaidak requested changes

2019-01-29 10:46 UTC, terrysahaidak commented on app/components/Item/ItemContainer.js
> +const mapStateToProps = (state) => ({});
тут цього не має бути точно

2019-01-29 10:46 UTC, terrysahaidak commented on app/components/Item/ItemContainer.js
> +  connect(
як і коннекту, той апдейт простіше прокинути через пропси зверху

2019-01-29 10:46 UTC, terrysahaidak commented on app/components/Item/ItemContainer.js
> +export default withNavigation(hoistStatics(enhance)(ItemView));
withNavigation можна першим аргументом в compose прокинути, так як це такий ж ХОК, як і всьо решту

2019-01-29 10:46 UTC, terrysahaidak commented on app/components/Item/ItemView.js
> +      <Text style={s.textTask}>{textItem}</Text>
тут в тебе стиль для тексту є, чому в текст-інпута немає такого ж?

2019-01-29 10:46 UTC, terrysahaidak commented on app/components/Item/ItemView.js
> +    <View style={s.containerEditing}>
є якесь пояснення для чого тут аж два контейнера?

2019-01-29 10:46 UTC, terrysahaidak commented on app/screens/Home/HomeScreenView.js
> +import ItemView from '../../components/Item/ItemContainer';
чого тут ItemView? можна ж просто Item
крім того, в `components` має бути `index.js`, в якому ти будеш експорт робити усіх компонентів, відповідно імпорт буде `import { TaskItem } from '../../components'`

Крім того, як я досі не помітив, шо в тебе компонент називається Item
Айтем шо? Якщо додати логіни, багато різних списків і прочі ніштяки, де буде багато компонентів, хто догадається шо Item це компонент, який відображає одну тудушку?

2019-01-29 11:15 UTC, terryperun commented on app/components/Item/ItemContainer.js
> +export default withNavigation(hoistStatics(enhance)(ItemView));
прокинув і забрав

2019-01-29 11:16 UTC, terryperun commented on app/components/Item/ItemView.js
> +      <Text style={s.textTask}>{textItem}</Text>
стиль помилково видалив, в стилях сам обєкт стилів був

2019-01-29 11:16 UTC, terryperun commented on app/components/Item/ItemView.js
> +    <View style={s.containerEditing}>
зайву вкладеність видалив

2019-01-29 12:09 UTC, terryperun commented on app/screens/Home/HomeScreenView.js
> +import ItemView from '../../components/Item/ItemContainer';
назви привів до порядку
імпорти поправив

2019-01-29 12:11 UTC, terrysahaidak requested changes

2019-01-29 12:11 UTC, terrysahaidak commented on app/components/index.js
> +export { ItemTodo, DoneBtn };
нє, не так
`export { default as TodoItem } from './TodoItem/TodoItemContainer'`

ну і напиши слово button нормально

2019-01-29 13:11 UTC, terrysahaidak requested changes

2019-01-29 13:11 UTC, terrysahaidak commented on app/screens/Home/styles.js
> +  DoneButton: {
а стилі ти нашо з великої написав?)

2019-01-30 09:30 UTC, terrysahaidak approved these changes

2019-01-30 09:30 UTC, merged